name: ICSID Monitor

on:
  schedule:
    - cron: '0 12 * * *'  # Diario a las 12:00 UTC (9:00 ARG)
  workflow_dispatch:      # Ejecutar manualmente

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run monitor
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python monitor.py
      
    - name: Commit data file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add icsid_data.json
        git diff --staged --quiet || git commit -m "Update ICSID data"
        git push